### PR TITLE
EPIC: School and Term validations - B1

### PR DESCRIPTION
**Pull request by golo230**
implemented the school table's entity and controller

Closes issue https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-4/issues/56: [EPIC 1] Entity and Repository class for schools table

### CODE REVIEW

**Review by AnikaArora — APPROVED** [review]
Code looks good! Few PR-related changes: 
- More detailed name 
- What issue does it close? 

Once you make these changes, have a team member take a look as well and then go ahead and merge!

**Comment by golo230** [comment]
Closes issue #56: [EPIC 1] Entity and Repository class for schools table

**Review by whuang602 — COMMENTED** [review]
You can add the comment content to the PR description itself.

**Comment by AnikaArora** [comment]
> You can add the comment content to the PR description itself.

Yes, please do this!

**Review by AdmPenguin — APPROVED** [review]
LGTM

**Pull request merged**
