### PR TITLE
Bug 5 icon

### PR DESCRIPTION
**Pull request by Aavash-Adhikari**
Not finished, original icon not showing up on website and by extension updated icon also not showing up. Need help in lecture.

### CODE REVIEW

**Review by whuang602 — CHANGES_REQUESTED** [review]
Please make sure the image is copyright free. Or if you generated it with AI software. If so, make sure you own the rights to the image.

Please also include links/proof of your rights as stated by the entity that produced the generation tool.

**Comment by Aavash-Adhikari** [comment]
> Please make sure the image is copyright free. Or if you generated it with AI software. If so, make sure you own the rights to the image.
> 
> Please also include links/proof of your rights as stated by the entity that produced the generation tool.
Screenshot 2024-03-14 at 1 12 20 PM (1)

**Review by luxiangzh — CHANGES_REQUESTED** [review]
Use transparent background

**Review by golo230 — APPROVED** [review]
LGTM

**Comment by luxiangzh** [comment]
Screenshot_2024-03-15_14-57-48

**Review by whuang602 — CHANGES_REQUESTED** [review]
The problem isn't the image itself. We need to know  that the image is copy right free and see proof that it is copy right free (links, etc) if it's created by you without the use of external tools, such as image generators.

**Comment by luxiangzh** [comment]
> The problem isn't the image itself. We need to know that the image is copy right free and see proof that it is copy right free (links, etc) if it's created by you without the use of external tools, such as image generators.

I understand the importance of ensuring our project uses copyright-free images. The icons I've proposed are generated using DALL·E, a tool by OpenAI, which grants users full ownership of the created images, including the rights to reprint, sell, and merchandise. According to OpenAI's policy, as the creator, I hold the copyright to these images, making them legitimately usable for our project. Here're the links to OpenAI's policy for your reference: 
https://openai.com/policies/terms-of-use
https://help.openai.com/en/articles/6425277-can-i-sell-images-i-create-with-dall-e

Screenshot_2024-03-16_12-44-27
Screenshot_2024-03-16_12-45-37

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
