### PR TITLE
fixed footer typo

### LINKED ISSUE #3: BUG: It's a Typo in the Footer
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

There is a typo in the footer of the organic web app. (5)

### Expected Behavior

It's vs its, completely different meaning. "It's" = it is and "its" mean belonging to it.

The footer should state "Its purpose..." as opposed to "It's purpose..."

### Current / Observed Behavior

Currently the sentence says "It's purpose" which means It is purpose as opposed to purpose of it.

### Steps to Reproduce

1. Bottom of the front page
2.
3.
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by Aavash-Adhikari**
Closes #3 
Fixed footer error and test for footer.

image

### CODE REVIEW

**Comment by Aavash-Adhikari** [comment]
Fixed footer error and test for footer.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Can you provide images and/or deployment link?

**Review by djoyneruscb — DISMISSED** [review]
Changes look good to me, typos properly changes, as well as the corresponding tests.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Can you change the directory name as well as the import for Interceptors to be lowercase "interceptor"?

**Review by andrewpengucsb — CHANGES_REQUESTED** [review]
No description is frankly unacceptable, please update with at least a couple sentences about what what changed in the PR and mention what issue the PR closes. Also since this is a frontend issue please add a screenshot

**Review by luxiangzh — APPROVED** [review]
LGTM

**Review by andrewpengucsb — APPROVED** [review]

**Pull request merged**
