### PR TITLE
LZ - Complete EPIC 2 F5 and Fix Storybook Entries of Course Table and Pages

### LINKED ISSUE #59: [EPIC 2] The create pages takes in the github id, and passes it to the backend. On success, the user is routed back to the index page for the course staff for that course. On failure, an error message is shown. **EXTRA NOT REQUIRED

### LINKED ISSUE #60: [EPIC 2]  The course staff page has a button: add staff member that takes you to a page at a frontend url called /courses/{courseId}/staff/create **EXTRA NOT REQUIRED

### LINKED ISSUE #61: [EPIC 2] There is an AddCourseStaffForm that has a single field: one where you enter the githubLogin of a new staff member, along with tests and a storybook entry. The field must be nonblank. ** EXTRA NOT REQUIRED

### LINKED ISSUE #85: [EPIC 2] Fix Storybook Entries of CourseTable, CourseIndexPage and CourseEditPage

### PR DESCRIPTION
**Pull request by luxiangzh**
Dev Deployment: https://organic-luxiangzh-dev.dokku-12.cs.ucsb.edu/

Storybook Link: https://ucsb-cs156-w24.github.io/proj-organic-w24-6pm-4/prs/75/storybook

Frontend Screenshots:
Screenshot_2024-03-09_02-13-33
Screenshot_2024-03-09_02-10-04

This PR introduces the `AddCourseStaffForm` component to facilitate the addition of new course staff members via their GitHub ID. The form, accessible at `/courses/{courseId}/staff/create`, features a mandatory field for entering the GitHub ID as well as a read-only field of Course ID which is automatically populated based on the `{courseId}` parameter in the URL. Upon successful submission, the form sends both the auto-filled Course ID and the entered GitHub ID to the backend, after which the user is redirected to the staff index page of that specific course. In case of a submission failure, an error message is displayed to the user.

We take the githubLogin instead of the githubId as the user input on the frontend of addStaff for the following three main considerations:
- The backend POST endpoint specifically requires githubLogin as a parameter.
- The backend will automatically look up the githubId that matches the login.
- Users are generally more familiar with their GitHub logins, while GitHub IDs are usually hidden from user end.

Closes #59 Closes #60 Closes #61 Closes #85

### CODE REVIEW

**Review by djoyneruscb — DISMISSED** [review]
All the file changes appear to be sane, screen shots show the proper changes. Everything seems to be good. Good job.

**Review by djoyneruscb — DISMISSED** [review]
Changes look good, file changes look sane. Good Job.

**Review by golo230 — DISMISSED** [review]
LGTM

**Review by golo230 — DISMISSED** [review]
LGTM

**Review by golo230 — APPROVED** [review]
LGTM

**Review by whuang602 — COMMENTED** [review]
I am not exactly sure what dokku.env is but otherwise it looks good.

**Comment by luxiangzh** [comment]
> I am not exactly sure what dokku.env is but otherwise it looks good.

`dokku.env` is where I save my dokku app config to simplify deployment. It was added to `.gitignore` to avoid being committed by accident.

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
