### PR TITLE
LZ - Complete EPIC 2 F4

### LINKED ISSUE #55: [EPIC 2] "Staff" button on course table /courses/{courseId}/staff **EXTRA NOT REQUIRED

### LINKED ISSUE #58: [EPIC 2] Table component to list staff members and fixtures that match the GET /api/course/staff/all?courseId=123

### LINKED ISSUE #62: [EPIC 2] The staff table has a delete button that invokes the DELETE endpoint for that staff member.**EXTRA NOT REQUIRED

### LINKED ISSUE #63: [EPIC 2] The page /courses/{courseId}/staff retrieves the data from the backend and shows the staff for that course **EXTRA NOT REQUIRED

### PR DESCRIPTION
**Pull request by luxiangzh**
Storybook link: https://ucsb-cs156-w24.github.io/proj-organic-w24-6pm-4/prs/74/storybook/

Frontend Screenshots:
Screenshot_2024-03-08_23-13-12
Screenshot_2024-03-08_23-11-50
Screenshot_2024-03-08_23-12-04
Screenshot_2024-03-08_23-16-35
Screenshot_2024-03-08_23-12-57
Screenshot_2024-03-08_23-12-41
Screenshot_2024-03-08_23-15-18

This PR introduces functionality for managing course staff members through the frontend. A new "Staff" button has been added to the course table, which redirects users to the dedicated staff management page `/courses/{courseId}/staff`. This page is designed to interact with the backend's staff-related endpoints, enabling both the retrieval and deletion of staff member data. Corresponding tests and storybook entries have also been included.

Closes #55 Closes #58 Closes #62 Closes #63

### CODE REVIEW

**Review by whuang602 — CHANGES_REQUESTED** [review]
Explain more in the PR description. What does this accomplish?

**Review by AdmPenguin — DISMISSED** [review]
LGTM

**Review by golo230 — APPROVED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
